e_shop_project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls'))
   
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home,name="home"),
    path('category/', views.Category,name="category"),
    path('search/', views.search,name="search"),
    path('product/<int:id>',views.product,name='product'),
    path('checkout/<int:id>',views.checkout,name='checkout'),
    path('tracker',views.tracker,name='tracker'),
    path('cart_checkout',views.cart_checkout,name="cart_checkout")


    
   
]  

shop/models.py
from django.db import models

# Create your models here.
class Banner(models.Model):
    image=models.ImageField(upload_to="media/images",default='')

class Product(models.Model):
    name = models.CharField(max_length=60)
    price= models.IntegerField(default=0)
    description= models.CharField(max_length=200,default='')
    category = models.CharField(max_length=60,default='')
    shipping = models.CharField(max_length=60,default='Free')
    size =   models.CharField(max_length=60,default='')
    returnable = models.CharField(max_length=20,default='YES')
    image = models.ImageField(upload_to="media/images",default='')  



    def __str__(self):
        return self.name 

class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE) 
    image =  models.ImageField(upload_to="media/images",default='')  

    def __str__(self):
        return '{}'.format(self.product.id) 

class Order(models.Model):
    order_id=models.AutoField(primary_key=True)
    item = models.CharField(max_length=5000)  
    name=models.CharField(max_length=90)
    size=models.CharField(max_length=90)
    address=models.CharField(max_length=1000)
    state=models.CharField(max_length=111)
    Landmark=models.CharField(max_length=111)
    district=models.CharField(max_length=111)
    pin_code=models.CharField(max_length=111)
    phone=models.CharField(max_length=111,default='')
     
    def __str__(self):
        return '{}'.format(self.order_id)

class updateOrder(models.Model):
    update_id=models.AutoField(primary_key=True)
    order_id=models.IntegerField(default='')
    update_desc=models.CharField(max_length=5000) 
    timestap=models.DateField(auto_now_add=True)         
    
    def __str__(self):
        return self.update_desc

shop/views.py
from django.shortcuts import render
from .models import Banner,Product,Order,updateOrder
from django.http import HttpResponse
# Create your views here.
#home view
def home(request):
    image=Banner.objects.all()
    product = Product.objects.all()[0:12]
    return render(request,'base.html',{'banner':image,'product':product})

#show product by category
def Category(request):
    category=request.GET.get('category')
    product = Product.objects.filter(category=category)
    return render(request,'category.html',{'category':category,'product':product})
#search product
def search(request):
    try:
        query=request.GET.get("search")
    except:
        query=None 
    products=Product.objects.filter(name__icontains=query) 
    params={'product':products}
    return render(request,'search.html',params)    

#product view
def product(request,id):
    product=Product.objects.get(id=id) 
    return render(request,'product.html',{'product':product})   

#checkout view
def checkout(request,id):
    if request.method=="POST":
        name=request.POST.get('name','')
        size=request.POST.get('size','')
        Landmark=request.POST.get('landhouse')
        address=request.POST.get('address','')
        district=request.POST.get('district','')
        state=request.POST.get('state','')
        phone=request.POST.get('phone','')
        pin_code=request.POST.get('pincode','')
        itemjson=request.POST.get('itemjson','')
        order =Order(name=name,size=size,address=address,district=district,phone=phone,state=state,pin_code=pin_code,item=itemjson,Landmark=Landmark)
        order.save()
        update=updateOrder(order_id=order.order_id,update_desc="order has been placed,You will get tracking link after 3-4 days")
        update.save()
        return render(request,'success.html',{'order_id':order.order_id,'name':name})
#view for get request
    product=Product.objects.get(id=id) 
    return render(request,'checkout.html',{'product':product}) 


#add to cart checkout
def cart_checkout(request):
    if request.method=="POST":
        itemjson=request.POST.get('itemjson','')
        name=request.POST.get('name','')
        Landmark=request.POST.get('landhouse')
        address=request.POST.get('address','')
        district=request.POST.get('district','')
        state=request.POST.get('state','')
        phone=request.POST.get('phone','')
        pin_code=request.POST.get('pincode','')
        order =Order(name=name,address=address,district=district,phone=phone,state=state,pin_code=pin_code,item=itemjson,Landmark=Landmark)
        order.save()
        update=updateOrder(order_id=order.order_id,update_desc="order has been placed,You will get tracking link after 3-4 days")
        update.save()
        return render(request,'success.html',{'order_id':order.order_id,'name':name})
    return render(request,'cart_checkout.html')


    
#track the order
def tracker(request):
    if request.method=="POST":
        orderid=request.POST.get('orderid','')
        try:
            order=updateOrder.objects.filter(order_id=orderid)
            if len(order)>0:
                update=updateOrder.objects.filter(order_id=orderid)
                return render(request,'tracker.html',{'update':update})  
            else:
                return render(request,'tracker.html',{'nothing':'nothing'})
        except Exception as e:        
                return render(request,'tracker.html',{'nothing':'nothing'})
    return render(request,'tracker.html') 

shop/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <title>expense {% block title %} {% endblock %}</title>

    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Favicons -->
 


   
    <!-- Custom styles for this template -->
  
  </head>
  <body>
    
    
    <!--
       <img class="d-block w-100" src="/media/{{i.image}}" alt="First slide">
    -->  
 
     
        
            {% block content %}
            <!--navbar-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <a class="navbar-brand" href="#">Logo</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="#">Mens <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Womens</a>
                  </li>
             
              
                </ul>
                <form class="form-inline my-2 my-lg-0">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
              </div>
            </nav>
            <!--banner-->
             
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <img class="d-block w-100" src="/media/media/images/b1.jpeg" alt="First slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="/media/media/images/b2.jpeg" alt="Second slide">
                </div>
                <div class="carousel-item">
                  <img class="d-block w-100" src="/media/media/images/b3.jpeg" alt="Third slide">
                </div>
              </div>
              <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
           <!--team-->  

            
            
      
         
           

            {% endblock %}
          <!--footer-->
          <section id="footer" class="py-5">

            <div class="container py-5">
            <div class="row">
            <div class="col-lg-4 col-md-6 py-3">
            <div class="text-left">
             
             <h3> Our Mission </h3>
             
            <p class="text-muted"> Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
             
            
            </div>
            </div>
            <div class="col-lg-4 col-md-6 py-3">
            <div class="text-left">
             
             
            <h3> Where We Work</h3>
            <div><i class="fa fa-map-marker" aria-hidden="true"></i><span class="text-muted">Jumblo park, Nalasopara,Mumbai</span>  </div>
             <div><i class="fa fa-phone" aria-hidden="true"></i><span class="text-muted">9983894985</span>  </div>
            <div><i class="fa fa-envelope" aria-hidden="true"></i><span class="text-muted">chaurasiya383@gmail.com</span>  </div>
             
            
            </div>
            </div>
            <div class="col-lg-4 col-md-6 py-3">
            <div class="text-left">
             
            <h3>Follow Us</h3>
            <p class="text-muted"> Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
             
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-twitter"></a>
            <a href="#" class="fa fa-instagram"></a>
            </div>
            </div>
            </div>
            </div>
            </section>
     
      
   
  
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>
 

shop/templates/cart_checkout.html
{% extends 'base.html' %}
{% block title %} checkout{% endblock %}
{% block content %}
 
<!--demo-->
 
<div class="container py-3">
  <div>
    <ul class="list-group" id='item'>
      
      </ul>
   
  </div>
    <div class="row" id="details">
        <div class="col-lg-6">
            <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Item</th>
                      <th scope="col">Qty</th>
                      <th scope="col">Size</th>
                      <th scope="col">Price</th>
                      <th scope="col"></th>
                    </tr>
                  </thead>
                  <tbody id="rowitem"> 
                   
              
                  
                
                
                  </tbody>
                </table>
              </div>
              <div class="text-right" id="bill">
                 
                 
              </div>
        </div>
        <div class="col-lg-6">
            <h5 class="font-weight-bold py-2"> Delivery Address</h5>
            <form method="POST" action="{% url 'cart_checkout' %}" onsubmit="Sendform()">  {% csrf_token  %}
                <input type="hidden" name="itemjson" id="itemjson" >
                
                <div class="form-row">
                  <div class="form-group col-md-6 col-lg-12">
                    <label for="inputEmail4">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" required>
                  </div>
                  
                </div>
                <div class="form-group">
                    <label for="inputtel">Mob No</label>
                    <input type="tel" class="form-control" id="mob" name="phone" placeholder="Enter Number" max="10" required>
                  </div>
                <div class="form-group">
                  <label for="inputAddress">Address</label>
                  <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required>
                </div>
                <div class="form-group">
                  <label for="inputAddress2">Landmark & House no</label>
                  <input type="text" class="form-control" name="landhouse" id="inputAddress2" placeholder="Apartment, studio, or floor">
                </div>
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="inputCity">District</label>
                    <input type="text" class="form-control" id="city" name="district" placeholder="city name" required>
                  </div>
                  <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" name="state" placeholder="Enter state" required>
                  </div>
                  <div class="form-group col-md-2">
                    <label for="inputZip">Pin code</label>
                    <input type="text" class="form-control" id="Zip" name="pincode" placeholder="pin_code" required>
                  </div>
                </div>
               
                <button type="submit" class="btn btn-primary">Place order</button>
              </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
       if($.isEmptyObject(cart)){
        str=`<div class="alert alert-danger" role="alert">
  Cart is empty
</div>`
        $('#item').append(str);
        $('#details').hide();
    } 
    else{
      var total_bill=0
        for(var item in cart){
      
        let qty=cart[item][0]
        let name=cart[item][1]
        let price=cart[item][2]
        total_bill=total_bill+qty*price
        let str=`   <tr>
          <th scope="row">${name}</th>
                      <td> <input type="number" value='${qty}' class="form-control qty" id="${item}" min="1" oninput="Set_qty(this)" onfocusout="Set_correct(this)" required></td>
                      <td><input type="text" value='' class="form-control size" id="${item}" min="L" oninput="Set_size(this)"></td>
                      <td><span id="${item}" class="price">${price}</span> </td>
                     
                      <td><button type="button" id="${item}" class="btn btn-danger" onclick="Close(this)">x</button></td>
                    </tr>  `
            $('#rowitem').append(str)
        
   
    }
    let bill_str=`<b>Total:&#8377;<span id="total-bill">${total_bill}</span></b>`
    $('#bill').append(bill_str) 

  }
  //delete item
  function Close(e){
    var qtyelement = document.getElementsByClassName('qty');
    var priceelement = document.getElementsByClassName('price');
    var billelement = document.getElementById('total-bill');
    for (i = 0; i < qtyelement.length; i++){
       if(qtyelement[i].id==e.id){
         var qty = qtyelement[i].value
         var price = priceelement[i].innerText
         billelement.innerText = billelement.innerText-(qty*price);
         e.parentElement.parentElement.remove()
         delete cart[e.id]
         localStorage.setItem('cart',JSON.stringify(cart))
         document.getElementById('cart_no').innerText=Object.keys(cart).length
         
       }
    }

   // e.parentElement.parentElement.remove()






   
  }
  //update size
  function Set_size(e){
     if(e.value!==''){
       cart[e.id][3]=e.value
      
       localStorage.setItem('cart',JSON.stringify(cart))
  
     }
  }
  //set correct value in input box
  function Set_correct(e){
    if(isNaN(e.value) || e.value<=0){
      e.value =1
    }
  }
   
         
      
       
    function Set_qty(e){
      var total=0
      var qtyelement = document.getElementsByClassName('qty');
    var priceelement = document.getElementsByClassName('price');
    var billelement = document.getElementById('total-bill');
     if(e.value!=''){
      cart[e.id][0]=e.value
      
      localStorage.setItem('cart',JSON.stringify(cart))
      //call total fn
      calculate_total();
    
       
       
     
     }
  }
  //total bill 
  var billelement = document.getElementById('total-bill');
  function calculate_total(){
    var total =0;
    for(var item in cart){
      
      let qty=cart[item][0]
    
      let price=cart[item][2]
      total=total+qty*price
    }
    billelement.innerText =total;
  }
  
//submit form
function Sendform(){
  $('#itemjson').val(JSON.stringify(cart))
  localStorage.clear();
}
//disable input box
</script>
{% endblock %}

shop/templates/category.html
{% extends 'base.html' %}
{% block title%} {{category}} {% endblock%}
{% block content %}
 <h3 class="head text-center py-2">{{category}}</h3>
 <section id="trending">
              
             
  
  <div class="d-flex flex-row flex-wrap px-4">
    {% for item in product %}
    
      <div class="card" style="width: 18rem;">
        <a href="{% url 'product' item.id %}" class="custom-card">
          <img class="card-img-top" src="/media/{{item.image}}" style="height: 300px;" loading="lazy">
        </a>
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div>
              <span class="" id="namepr{{item.id}}">{{item.name}}</span></br>
              &#8377;<span  id="pricepr{{item.id}}">{{item.price}}</span>
            </div>
            <div>
              <span id="divpr{{item.id}}" class="divpr">
                <a  id="pr{{item.id}}" class="btn btn-warning btn-sm cart">ADD TO CART</a>
              </span>
            </div>
          </div>
        </div>
      </div>
    
    
       
    {% endfor %}
  </div>
  
 
</section>
{% endblock content %}

shop/templates/checkout.html
{% extends 'base.html' %}
{% block title %} checkout{% endblock %}
{% block content %}
 
<!--demo-->
<div class="container py-3">
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-group">

                <li class="list-group-item active font-weight-bold">Order Summary</li>
                <input type="hidden" name="id" id="pro_id" value="{{product.id}}">
                <li class="list-group-item"><b>Name:</b> <span id="pro_name">{{product.name}} </span>   </li>
                <li class="list-group-item"><b>Price:</b>  &#8377; {{product.price}}  </li>
                <li class="list-group-item"><b>Quantity:</b>
                     <input type="number" value='1' class="form-control" id="qty" min="1" oninput="calculate(this.value)" required>  </li>
                <li class="list-group-item text-right"><b>Total:</b>   <span id="price">{{product.price}}  </span> </li>
                
               
    
              </ul>
        </div>
        <div class="col-lg-6">
            <h5 class="font-weight-bold py-2"> Delivery Address</h5>
            <form method="POST" action="{% url 'checkout' product.id %}" onsubmit="Inform()">  {% csrf_token  %}
                <input type="hidden" name="itemjson" id="itemjson" >
                
                <div class="form-row">
                  <div class="form-group col-md-6" id="namediv">
                    <label for="inputEmail4">Name</label>
                    <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name" required>
                  </div>
                  <div class="form-group col-md-6" id="size">
                    <label for="inputPassword4">Product Size</label>
                    <input type="text" class="form-control"  name="size" placeholder="L,M,XL" required>
                  </div>
                </div>
                <div class="form-group">
                    <label for="inputtel">Mob No</label>
                    <input type="tel" class="form-control" id="mob" name="phone" placeholder="Enter Number" max="10" required>
                  </div>
                <div class="form-group">
                  <label for="inputAddress">Address</label>
                  <input type="text" class="form-control" id="address" name="address" placeholder="1234 Main St" required>
                </div>
                <div class="form-group">
                  <label for="inputAddress2">Landmark & House no</label>
                  <input type="text" class="form-control" name="landhouse" id="inputAddress2" placeholder="Apartment, studio, or floor">
                </div>
                <div class="form-row">
                  <div class="form-group col-md-6">
                    <label for="inputCity">District</label>
                    <input type="text" class="form-control" id="city" name="district" placeholder="city name" required>
                  </div>
                  <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" name="state" placeholder="Enter state" required>
                  </div>
                  <div class="form-group col-md-2">
                    <label for="inputZip">Pin code</label>
                    <input type="text" class="form-control" id="Zip" name="pincode" placeholder="pin_code" required>
                  </div>
                </div>
               
                <button type="submit" class="btn btn-primary">Place order</button>
              </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
     //disable input box for watch
    var prodname= document.getElementById('pro_name')
    
    var res = prodname.innerText.match(/watch/gi)
    console.log(res)
    if(res){
      document.getElementById('size').style.display='none'
      document.getElementById('namediv').classList.add('col-lg-12')
    }
   
     console.log(prodname)
    //calculate total price
         var qty = document.getElementById('qty');
    var price = Number(document.getElementById('price').innerText);
    var pricehtml = document.getElementById('price');
    function calculate(e){
    
        if(qty.value!=0)
        {
        quantity = Number(e)
            var total=price*quantity;
        pricehtml.innerText=total;
       
        }    
    }
   //create cart store info
   function Inform(){
     
      carts = {}
      carts['name'] = document.getElementById('pro_name').innerText;
      carts['quantity'] =$('#qty').val();
      carts['price'] = document.getElementById('price').innerText;
      $('#itemjson').val(JSON.stringify(carts))
      
      
   }

</script>
{% endblock %}

shop/templates/product.html
{% extends 'base.html' %}
{% block title%} {{product.name}}{% endblock%}
{% block content %}
 
 
 <!--demo--> 
 <div class="container">
    <div class="row">
         
        <div class="col-lg-6">
          <div class="mySlides">
            
  <img class="d-block w-100 img-fluid MainImage" src='/media/{{product.image}}' style="width:100%" id="mainImage" loading="lazy">
</div>

 
 <div class="gallery">
    <div class="row">
        {% for pi in product.productimage_set.all %}
        <div class="column">
          
          <img class="demo cursor" src="/media/{{pi.image}}" style="width:100%" id="" onclick="ChangeImage(this)" loading="lazy">
        </div>
       
       {% endfor %}
        
       
      </div>
 </div>
  
 
    </div>
        <div class="col-lg-6">
          <ul class="list-group">
              <li class="list-group-item active font-weight-bold">Product Details</li>
              <li class="list-group-item"><b>Name:</b> {{product.name}} </li>
              
              <li class="list-group-item"><b>Price:&#8377;</b>{{product.price}} </li>
              <li class="list-group-item"><b>Description:</b>  {{product.description}}</li>
              <li class="list-group-item"><b>Available Size:</b>  {{product.size}}</li>
              <li class="list-group-item"><b>Shipping Charge:</b>  {{product.shipping}}</li>
              <li class="list-group-item"><b>Returnable:</b>  <span class="text-success">{{product.returnable}}</span>  </li>
              <li class="list-group-item"><b>Payment:</b> Cash on Delivery   </li>
            </ul>
            <div class="py-3">
              
                
              
                
              
               
              <a type="button" href="{% url 'checkout'  product.id %}" class="btn btn-primary font-weight-bold">BUY NOW</a>
            </div>
      </div>
     
       
</div>
</div>
{% endblock content %}



{% block js %}
 <script>
   function ChangeImage(e){
     document.getElementById('mainImage').src=e.src 
   }
    
       // add inc, dec button in cart button
         
    
 </script>
       
 
{% endblock %}
 

 
 
<!--jh-->
 

shop/templates/search.html
{% extends 'base.html' %}
{% block title%} search {% endblock%}
{% block content %}
 
 <section id="">
              
         {% if product %}    
  
  <div class="d-flex flex-row flex-wrap px-4">
    {% for item in product %}
     
      <div class="card" style="width: 18rem;">
        <a href="{% url 'product' item.id %}" class="custom-card">
          <img class="card-img-top" src="/media/{{item.image}}" style="height: 300px;" loading="lazy">
        </a>
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <div>
              <span class="" id="namepr{{item.id}}">{{item.name}}</span></br>
              &#8377;<span  id="pricepr{{item.id}}">{{item.price}}</span>
            </div>
            <div>
              <span id="divpr{{item.id}}" class="divpr">
                <a  id="pr{{item.id}}" class="btn btn-warning btn-sm cart">ADD TO CART</a>
              </span>
            </div>
          </div>
        </div>
      </div>
    
    
       
    {% endfor %}
    {% else %}
    <h3 class="text-center text-danger">Sorry,no result found!</h3>
    <p class="text-center text-muted"> Please check the spelling   </p>
    {% endif %}
  </div>
  
 
</section>
{% endblock content %}

shop/templates/success.html
{% extends 'base.html' %}
{% block title%} confirm order {% endblock%}
{% block content %}
 <div class="container">
    <div class="alert alert-success py-2" role="alert">
        <h4 class="alert-heading">Confirm Order!</h4>
        <p>Thank you {{name}}, for order</p>
        <hr>
        <b>Note:-</b><span>Your Order ID is {{order_id}},You can track your order using this ID</span>
      </div>
      <div class="text-center">
        <a  href="/" type="button" class="btn btn-primary">Back to Home</a>
      </div>
       
 </div>
{% endblock content %}

shop/templates/tracker.html
{% extends 'base.html' %}
{% block title%} tracker {% endblock%}
{% block content %}
 <div class="container py-5">
    <form method="POST" action="{% url 'tracker' %}">  {% csrf_token  %}
        <div class="row">
          <div class="col py-2">
            <input type="text" class="form-control" placeholder="tracking id" name="orderid" required>
          </div>
          <div class=" col py-2">
            <button type="submit" style ="color:white !important;" class="btn btn-primary px-3">Track</button>
          </div>
        </div>
      </form>

      <div>
       
       {% if update %}
        
       <ul class="list-group">
        <li class="list-group-item active">Update Details</li>
        {% for i in update %}
        <li class="list-group-item"> 

            <div class="alert alert-success" role="alert">
                {{i}}
              </div>
        </li>
        {% endfor %}
      </ul>
        

       {% endif %}
  </div>
  {% if nothing %}
  <div class="alert alert-danger" role="alert">
    Sorry, You have provided wrong order ID
  </div>
  {% endif %}
       
 </div>
 <br>
 <br>
 <br>
 <br>
 <br>
{% endblock content %}

{% block js %}

 

{% endblock %}